export const TRASH_COPY = {
  navLabel: "ნაგვის ყუთი",
  pageTitle: "ნაგვის ყუთი",
  pageDescription: "წაშლილი განცხადებები და კლიენტები. მხოლოდ ადმინს შეუძლია აღდგენა ან სამუდამოდ წაშლა.",
  propertiesTab: "განცხადებები",
  clientsTab: "კლიენტები",
  propertiesCount: "განცხადებები",
  clientsCount: "კლიენტები",
  restore: "აღდგენა",
  permanentDelete: "სამუდამოდ წაშლა",
  deletedAtLabel: "წაშლილია",
  deletedFromArchive: "არქივიდან წაშლილი",
  emptyProperties: "წაშლილი განცხადებები არ არის",
  emptyClients: "წაშლილი კლიენტები არ არის",
  searchPlaceholder: "ძიება...",
  sortLabel: "სორტირება",
  sortDeletedAt: "წაშლის თარიღი",
  sortCreatedAt: "შექმნილია",
  sortUpdatedAt: "განახლებულია",
  orderDesc: "კლებადი",
  orderAsc: "ზრდადი",
  agentLabel: "აგენტი",
  statusLabel: "სტატუსი",
  backToTrash: "ნაგვის ყუთი",
  forbidden: "ამ გვერდზე წვდომა არ გაქვთ.",
  restored: "ჩანაწერი აღდგა",
  restoredToArchive: "ჩანაწერი დაბრუნდა არქივში",
  permanentlyDeleted: "ჩანაწერი სამუდამოდ წაიშალა",
  restoreFailed: "აღდგენა ვერ მოხერხდა.",
  permanentFailed: "სამუდამოდ წაშლა ვერ მოხერხდა.",
  notFound: "ჩანაწერი ვერ მოიძებნა.",
} as const;
