export const HIDDEN_PROPERTY_COPY = {
  hideAction: "დროებით დამალვა",
  hideSuccess: "ვარიანტი დროებით დამალულია ამ კლიენტისთვის",
  hideError: "ვარიანტის დამალვა ვერ მოხერხდა.",
  unhideAction: "ისევ გამოჩენა",
  unhideSuccess: "ვარიანტი კვლავ გამოჩნდება შესაბამისობებში, თუ მოთხოვნებს შეესაბამება",
  unhideError: "ვარიანტის გამოჩენა ვერ მოხერხდა.",
  sectionTitle: "დამალული ვარიანტები",
  emptyState: "დამალული ვარიანტები არ არის",
  archivedBadge: "არქივშია",
  hiddenAtPrefix: "დამალულია",
  loadingList: "დამალული ვარიანტები იტვირთება…",
  loadError: "დამალული ვარიანტების ჩატვირთვა ვერ მოხერხდა.",
  noAccess: "ამ კლიენტზე წვდომა არ გაქვთ",
  unauthorized: "ავტორიზაცია საჭიროა.",
  notFound: "ჩანაწერი ვერ მოიძებნა.",
  openListing: "განცხადების გახსნა",
} as const;
