const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..", "src");

const pairs = [
  ["Session-only. These are not saved on the client or property.", "მოქმედებს მხოლოდ მიმდინარე სესიაში და კლიენტზე ან განცხადებაზე არ ინახება."],
  ["Results use the backend match percentage. Order is preserved from the API.", "შედეგები ეყრდნობა სერვერის შესაბამისობის პროცენტს."],
  ["MINE uses your own clients, not the listing owner. Cards show public match fields only.", "ჩემი კლიენტები ნიშნავს თქვენს კლიენტებს და არა განცხადების მფლობელისას."],
  ["Not frozen — click to freeze as a hard matching lock", "არ არის გაყინული — დააჭირეთ მკაცრ პირობად გასაყინად"],
  ["Frozen hard lock — click to clear", "გაყინული მკაცრი პირობა — დააჭირეთ გასასუფთავებლად"],
  ["Phone number must be in international format, e.g. +995555111222", "ტელეფონი უნდა იყოს საერთაშორისო ფორმატში, მაგ. +995555111222"],
  ["Add at least one reminder with a valid date and time.", "დაამატეთ მინიმუმ ერთი შეხსენება სწორი თარიღითა და დროით."],
  ["Select the client you rented this property to.", "აირჩიეთ კლიენტი, რომელზეც გააქირავეთ ეს განცხადება."],
  ["Sign in to filter by your properties", "შედით სისტემაში თქვენი განცხადებების სანახავად"],
  ["Clear this field to remove the reminder.", "გაასუფთავეთ ეს ველი შეხსენების წასაშლელად."],
  ["Enter minimum rental period in months", "შეიყვანეთ მინიმალური ქირის ვადა თვეებში"],
  ["Min Rental Period must be a whole number of months.", "მინიმალური ქირის ვადა უნდა იყოს მთელი რიცხვი თვეებში."],
  ["Min Rental Period must be a whole number of at least 1 month.", "მინიმალური ქირის ვადა უნდა იყოს მინიმუმ 1 თვე."],
  ["Min Rental Period (months) is required.", "მინიმალური ქირის ვადა (თვეებში) სავალდებულოა."],
  ["Min Rental Period must be at least 1 month.", "მინიმალური ქირის ვადა უნდა იყოს მინიმუმ 1 თვე."],
  ["City must be one of თბილისი, ბათუმი, ქუთაისი, or ბორჯომი.", "ქალაქი უნდა იყოს თბილისი, ბათუმი, ქუთაისი ან ბორჯომი."],
  ["Budget min must be less than or equal to budget max", "მინიმალური ბიუჯეტი არ უნდა აღემატებოდეს მაქსიმალურს"],
  ["Rooms from must be less than or equal to rooms to", "ოთახების მინიმუმი არ უნდა აღემატებოდეს მაქსიმუმს"],
  ["Bedrooms from must be less than or equal to bedrooms to", "საძინებლების მინიმუმი არ უნდა აღემატებოდეს მაქსიმუმს"],
  ["Min floor must be less than or equal to max floor", "მინიმალური სართული არ უნდა აღემატებოდეს მაქსიმალურს"],
  ["Bathrooms from must be less than or equal to bathrooms to", "სველი წერტილების მინიმუმი არ უნდა აღემატებოდეს მაქსიმუმს"],
  ["Area from must be less than or equal to area to", "ფართობის მინიმუმი არ უნდა აღემატებოდეს მაქსიმუმს"],
  ["Balcony area min must be less than or equal to max", "აივნის ფართობის მინიმუმი არ უნდა აღემატებოდეს მაქსიმუმს"],
  ["You can upload at most 50 images.", "შეგიძლიათ ატვირთოთ მაქსიმუმ 50 ფოტო."],
  ["Name must be at least 2 characters", "სახელი უნდა შეიცავდეს მინიმუმ 2 სიმბოლოს"],
  ["At least one phone number is required.", "საჭიროა მინიმუმ ერთი ტელეფონის ნომერი."],
  ["At least one phone is required", "საჭიროა მინიმუმ ერთი ტელეფონი"],
  ["Select whole hotel or hotel room.", "აირჩიეთ მთელი სასტუმრო ან ნომერი."],
  ["Select land category and land usage.", "აირჩიეთ მიწის კატეგორია და დანიშნულება."],
  ["Failed to sign in with Google. Check console for details.", "Google-ით შესვლა ვერ მოხერხდა."],
  ["A date and time is required.", "თარიღი და დრო სავალდებულოა."],
  ["Land category is required.", "მიწის კატეგორია სავალდებულოა."],
  ["Land usage is required.", "მიწის დანიშნულება სავალდებულოა."],
  ["Hotel scope is required.", "სასტუმროს ტიპი სავალდებულოა."],
  ["Owner phone is required.", "მესაკუთრის ტელეფონი სავალდებულოა."],
  ["Owner name is required.", "მესაკუთრის სახელი სავალდებულოა."],
  ["District is required.", "უბანი სავალდებულოა."],
  ["Address is required.", "მისამართი სავალდებულოა."],
  ["City is required.", "ქალაქი სავალდებულოა."],
  ["Description is required", "აღწერა სავალდებულოა"],
  ["Name is required", "სახელი სავალდებულოა"],
  ["Phone cannot be empty", "ტელეფონი არ შეიძლება იყოს ცარიელი"],
  ["No changes to save.", "შესანახი ცვლილება არ არის."],
  ["Update the client's details below.", "განაახლეთ კლიენტის მონაცემები."],
  ["Update the client&apos;s details below.", "განაახლეთ კლიენტის მონაცემები."],
  ["Fill in the details below to create a new lead.", "შეავსეთ ქვემოთ მოცემული ველები ახალი კლიენტის დასამატებლად."],
  ["MyHome and SS.ge IDs with upload dates.", "MyHome-ისა და SS.ge-ის ID-ები ატვირთვის თარიღებით."],
  ["Add a district to get started.", "დაამატეთ უბანი დასაწყებად."],
  ["Add an address to get started.", "დაამატეთ მისამართი დასაწყებად."],
  ["Add a label to get started.", "დაამატეთ ლეიბლი დასაწყებად."],
  ["No related persons added.", "დაკავშირებული პირები არ არის დამატებული."],
  ["Type to search or add labels", "აკრიფეთ ლეიბლის მოსაძებნად ან დასამატებლად"],
  ["Type a label and press Enter", "აკრიფეთ ლეიბლი და დააჭირეთ Enter"],
  ["Type to search labels", "აკრიფეთ ლეიბლის მოსაძებნად"],
  ["Marked as needs verification", "მონიშნულია გადასამოწმებლად"],
  ["Mark as needs verification", "მონიშნეთ გადასამოწმებლად"],
  ["See and manage all properties", "განცხადებების ნახვა და მართვა"],
  ["Add new homes, update details, and keep everything tidy in one place.", "დაამატეთ ახალი განცხადებები და განაახლეთ დეტალები ერთ სივრცეში."],
  ["Look after your team", "გუნდის მართვა"],
  ["Invite new agents and keep track of who is working on what.", "მოიწვიეთ ახალი აგენტები და აკონტროლეთ სამუშაო."],
  ["What would you like to do?", "რისი გაკეთება გსურთ?"],
  ["Good to see you again", "კეთილი იყოს თქვენი მობრძანება"],
  ["You're signed in as", "შესული ხართ როგორც"],
  ["You&apos;re signed in as", "შესული ხართ როგორც"],
  ["to see only your listings.", "მხოლოდ თქვენი განცხადებების სანახავად."],
  ["Sign in to your account", "ანგარიშში შესვლა"],
  ["Sign in with Google to get started", "გასაგრძელებლად შედით Google-ით"],
  ["Signing you in...", "შესვლა მიმდინარეობს..."],
  ["Something went wrong", "რაღაც შეცდომა მოხდა"],
  ["Unable to load districts.", "უბნების ჩატვირთვა ვერ მოხერხდა."],
  ["No districts available.", "უბნები არ არის."],
  ["Select district group first", "ჯერ აირჩიეთ უბნების ჯგუფი"],
  ["Select neighborhood", "აირჩიეთ უბანი"],
  ["Select district group", "აირჩიეთ უბნების ჯგუფი"],
  ["Select hotel scope", "აირჩიეთ სასტუმროს ტიპი"],
  ["Quick select (months)", "სწრაფი არჩევა (თვეები)"],
  ["Filter by listing lifecycle status", "სტატუსით გაფილტვრა"],
  ["Filter by property type", "ტიპით გაფილტვრა"],
  ["Filter by deal type", "გარიგების ტიპით გაფილტვრა"],
  ["Filter by status", "სტატუსით გაფილტვრა"],
  ["Results per page", "შედეგები გვერდზე"],
  ["Sort listings by", "სორტირება"],
  ["Sort agents by", "აგენტების სორტირება"],
  ["Sort clients by", "კლიენტების სორტირება"],
  ["Sort direction", "მიმართულება"],
  ["Sort order", "სორტირების მიმართულება"],
  ["Listing actions", "განცხადების მოქმედებები"],
  ["Property list scope", "განცხადებების სია"],
  ["Property filters", "განცხადების ფილტრები"],
  ["Close filters", "ფილტრების დახურვა"],
  ["Close photo viewer", "ფოტოების დახურვა"],
  ["Previous photo", "წინა ფოტო"],
  ["Next photo", "შემდეგი ფოტო"],
  ["Previous image", "წინა ფოტო"],
  ["Next image", "შემდეგი ფოტო"],
  ["Photo viewer", "ფოტოების ნახვა"],
  ["Dismiss reminder alert", "შეხსენების დახურვა"],
  ["Client the property is rented to", "კლიენტი, რომელზეც არის გაქირავებული"],
  ["Find matching properties", "შესაბამისი განცხადებების ძიება"],
  ["Find matching clients", "შესაბამისი კლიენტების ძიება"],
  ["Matching properties", "შესაბამისი განცხადებები"],
  ["Matching clients", "შესაბამისი კლიენტები"],
  ["No matching properties.", "შესაბამისი განცხადებები ვერ მოიძებნა."],
  ["No matching clients.", "შესაბამისი კლიენტები ვერ მოიძებნა."],
  ["No matching properties", "შესაბამისი განცხადებები ვერ მოიძებნა"],
  ["No matching streets", "შესაბამისი ქუჩები ვერ მოიძებნა"],
  ["No matching labels", "შესაბამისი ლეიბლები ვერ მოიძებნა"],
  ["Temporary hard locks", "დროებითი მკაცრი პირობები"],
  ["No scored criteria.", "შეფასებული კრიტერიუმები არ არის."],
  ["Loading property details…", "განცხადების დეტალები იტვირთება…"],
  ["Loading your dashboard…", "მთავარი იტვირთება…"],
  ["Loading your session…", "სესია იტვირთება…"],
  ["Loading properties…", "განცხადებები იტვირთება…"],
  ["Loading reminders…", "შეხსენებები იტვირთება…"],
  ["Loading matches…", "შესაბამისობები იტვირთება…"],
  ["Loading clients…", "კლიენტები იტვირთება…"],
  ["Loading agents…", "აგენტები იტვირთება…"],
  ["Loading client…", "კლიენტი იტვირთება…"],
  ["No properties found.", "განცხადებები ვერ მოიძებნა."],
  ["No clients found.", "კლიენტები ვერ მოიძებნა."],
  ["No agents found.", "აგენტები ვერ მოიძებნა."],
  ["No reminders yet.", "შეხსენებები ჯერ არ არის."],
  ["No invite links yet.", "მოწვევის ბმულები ჯერ არ არის."],
  ["No comments yet.", "კომენტარები ჯერ არ არის."],
  ["No photo", "ფოტო არ არის"],
  ["Client invite links", "კლიენტის მოწვევის ბმულები"],
  ["Property requirements", "უძრავი ქონების მოთხოვნები"],
  ["Private house details", "კერძო სახლის დეტალები"],
  ["Apartment details", "ბინის დეტალები"],
  ["Land plot details", "მიწის ნაკვეთის დეტალები"],
  ["Commercial details", "კომერციული ობიექტის დეტალები"],
  ["Property details", "განცხადების დეტალები"],
  ["Related persons", "დაკავშირებული პირები"],
  ["Internal notes", "შიდა შენიშვნები"],
  ["Exclude last floor", "ბოლო სართულის გამოკლებით"],
  ["Exclude projects", "გამორიცხული პროექტები"],
  ["Central heating", "ცენტრალური გათბობა"],
  ["Air conditioner", "კონდიციონერი"],
  ["Building condition", "შენობის მდგომარეობა"],
  ["Kitchen type", "სამზარეულოს ტიპი"],
  ["Has balcony", "აივანი"],
  ["Good view", "კარგი ხედი"],
  ["Min rental period", "მინიმალური ქირის ვადა"],
  ["Balcony area (m²)", "აივნის ფართობი (მ²)"],
  ["Area (m²)", "ფართობი (მ²)"],
  ["Price per m²", "ფასი მ²-ზე"],
  ["Comment for myself", "შიდა კომენტარი"],
  ["Comment date", "კომენტარის თარიღი"],
  ["Owner WhatsApp", "მესაკუთრის WhatsApp"],
  ["Owner whatsapp", "მესაკუთრის WhatsApp"],
  ["Owner phones", "მესაკუთრის ტელეფონები"],
  ["Owner name", "მესაკუთრის სახელი"],
  ["Owner phone", "მესაკუთრის ტელეფონი"],
  ["Public price", "საჯარო ფასი"],
  ["Internal price", "შიდა ფასი"],
  ["External IDs", "გარე ID-ები"],
  ["Default (Active)", "ნაგულისხმევი (აქტიური)"],
  ["Not specified", "არ არის მითითებული"],
  ["To be verified", "გადასამოწმებელია"],
  ["Unspecified", "არ არის მითითებული"],
  ["Doesn't matter", "არ აქვს მნიშვნელობა"],
  ["All listings", "ყველა განცხადება"],
  ["My listings", "ჩემი განცხადებები"],
  ["All clients", "ყველა კლიენტი"],
  ["My clients", "ჩემი კლიენტები"],
  ["My Properties", "ჩემი განცხადებები"],
  ["Your properties", "ჩემი განცხადებები"],
  ["Your agents", "ჩემი აგენტები"],
  ["Your links", "თქვენი ბმულები"],
  ["All deal types", "ყველა გარიგება"],
  ["All statuses", "ყველა სტატუსი"],
  ["All types", "ყველა ტიპი"],
  ["All deals", "ყველა გარიგება"],
  ["Listing status", "განცხადების სტატუსი"],
  ["Property type", "უძრავი ქონების ტიპი"],
  ["Deal type", "გარიგების ტიპი"],
  ["Create property", "განცხადების შექმნა"],
  ["Create link", "ბმულის შექმნა"],
  ["Save reminders", "შეხსენებების შენახვა"],
  ["Save changes", "ცვლილებების შენახვა"],
  ["Save client", "კლიენტის შენახვა"],
  ["Save agent", "აგენტის შენახვა"],
  ["Add property", "განცხადების დამატება"],
  ["Add client", "კლიენტის დამატება"],
  ["Add agent", "აგენტის დამატება"],
  ["Add more images", "მეტი ფოტოს დამატება"],
  ["Edit property", "განცხადების რედაქტირება"],
  ["Edit client", "კლიენტის რედაქტირება"],
  ["Edit reminder", "შეხსენების რედაქტირება"],
  ["Delete reminder", "შეხსენების წაშლა"],
  ["Delete comment", "კომენტარის წაშლა"],
  ["Delete this client?", "წავშალოთ ეს კლიენტი?"],
  ["Delete this agent?", "წავშალოთ ეს აგენტი?"],
  ["Remove this reminder?", "წავშალოთ ეს შეხსენება?"],
  ["Remove person", "პირის წაშლა"],
  ["Remove district", "უბნის წაშლა"],
  ["Remove address", "მისამართის წაშლა"],
  ["Remove label", "ლეიბლის წაშლა"],
  ["Remove phone", "ტელეფონის წაშლა"],
  ["Yes, delete", "დიახ, წაშლა"],
  ["Back to listing", "განცხადებაზე დაბრუნება"],
  ["Back to client", "კლიენტზე დაბრუნება"],
  ["Open listing", "განცხადების გახსნა"],
  ["Open client", "კლიენტის გახსნა"],
  ["Search properties…", "განცხადებების ძიება…"],
  ["Clear search", "ძიების გასუფთავება"],
  ["City contains…", "ქალაქი შეიცავს…"],
  ["District contains…", "უბანი შეიცავს…"],
  ["Select a client…", "აირჩიეთ კლიენტი…"],
  ["Write a comment…", "დაწერეთ კომენტარი…"],
  ["e.g. spouse, parent", "მაგ. მეუღლე, მშობელი"],
  ["e.g. dog, cat", "მაგ. ძაღლი, კატა"],
  ["Apartment or commercial", "ბინა ან კომერციული"],
  ["Frozen hard lock", "გაყინული მკაცრი პირობა"],
  ["Archive external ID", "გარე ID-ის დაარქივება"],
  ["ID number", "ID ნომერი"],
  ["Reminder due now", "შეხსენების დრო დადგა"],
  ["Reminder date", "შეხსენების თარიღი"],
  ["Link created", "ბმული შეიქმნა"],
  ["Copy this link:", "დააკოპირეთ ეს ბმული:"],
  ["Copy link", "ბმულის კოპირება"],
  ["Expires (optional)", "ვადა (არასავალდებულო)"],
  ["Max uses", "მაქს. გამოყენება"],
  ["Core info", "ძირითადი ინფორმაცია"],
  ["Private house", "კერძო სახლი"],
  ["Land plot", "მიწის ნაკვეთი"],
  ["Exact fields", "ზუსტი ველები"],
  ["Min price (₾)", "მინ. ფასი (₾)"],
  ["Max price (₾)", "მაქს. ფასი (₾)"],
  ["Min area (m²)", "მინ. ფართობი (მ²)"],
  ["Max area (m²)", "მაქს. ფართობი (მ²)"],
  ["Yard area", "ეზოს ფართობი"],
  ["House area", "სახლის ფართობი"],
  ["Land area", "მიწის ფართობი"],
  ["Commercial area", "კომერციული ფართობი"],
  ["High → low", "კლებადობით"],
  ["Low → high", "ზრდადობით"],
  ["Per page", "გვერდზე"],
  ["Go back", "უკან"],
  ["Redirecting…", "გადამისამართება…"],
  ["Loading...", "იტვირთება..."],
  ["Loading…", "იტვირთება…"],
  ["Creating…", "იქმნება…"],
  ["Saving…", "ინახება…"],
  ["Submitting…", "იგზავნება…"],
  ["1 month", "1 თვე"],
  ["3 months", "3 თვე"],
  ["6 months", "6 თვე"],
  ["12 months", "12 თვე"],
  [" · hard lock", " · მკაცრი პირობა"],
  ["Details completeness", "ინფორმაციის შევსება"],
  ["No districts", "უბნები არ არის"],
  ["Log out", "გასვლა"],
  ["Sign in", "შესვლა"],
  ["Thank you", "გმადლობთ"],
  ["Requirements", "მოთხოვნები"],
  ["Renovations", "რემონტი"],
  ["Renovation", "რემონტი"],
  ["Furnished", "ავეჯით"],
  ["Elevator", "ლიფტი"],
  ["Parking", "პარკინგი"],
  ["Bathrooms", "სველი წერტილები"],
  ["Bedrooms", "საძინებლები"],
  ["Comments", "კომენტარები"],
  ["Comment", "კომენტარი"],
  ["Apartment", "ბინა"],
  ["Commercial", "კომერციული"],
  ["Location", "მდებარეობა"],
  ["Addresses", "მისამართები"],
  ["Address", "მისამართი"],
  ["Districts", "უბნები"],
  ["District", "უბანი"],
  ["Description", "აღწერა"],
  ["Relationship", "კავშირი"],
  ["Reminders", "შეხსენებები"],
  ["Properties", "განცხადებები"],
  ["Agents", "აგენტები"],
  ["Clients", "კლიენტები"],
  ["Dashboard", "მთავარი"],
  ["Filters", "ფილტრები"],
  ["Actions", "მოქმედებები"],
  ["Details", "დეტალები"],
  ["Created", "შექმნილია"],
  ["Updated", "განახლებულია"],
  ["Newest", "ახალი"],
  ["Joined", "შემოუერთდა"],
  ["Effective", "მიმდინარე"],
  ["Expires", "ვადა"],
  ["Copied", "დაკოპირებულია"],
  ["Copy", "კოპირება"],
  ["Budget min", "მინ. ბიუჯეტი"],
  ["Budget max", "მაქს. ბიუჯეტი"],
  ["Budget", "ბიუჯეტი"],
  ["Phones", "ტელეფონები"],
  ["Phone", "ტელეფონი"],
  ["Labels", "ლეიბლები"],
  ["Status", "სტატუსი"],
  ["Owner", "მესაკუთრე"],
  ["Price", "ფასი"],
  ["Rooms", "ოთახები"],
  ["Floor", "სართული"],
  ["Street", "ქუჩა"],
  ["City", "ქალაქი"],
  ["Name", "სახელი"],
  ["Email", "ელფოსტა"],
  ["Note", "შენიშვნა"],
  ["Type", "ტიპი"],
  ["Deal", "გარიგება"],
  ["Uses", "გამოყენება"],
  ["Due", "ვადა"],
  ["For", "ვისთვის"],
  ["Which", "რომელი"],
  ["Sort", "სორტირება"],
  ["From", "დან"],
  ["To", "მდე"],
  ["Min", "მინ."],
  ["Max", "მაქს."],
  ["Any", "ნებისმიერი"],
  ["Pets", "ცხოველები"],
  ["Pet", "შინაური ცხოველი"],
  ["Match", "ემთხვევა"],
  ["Mismatch", "არ ემთხვევა"],
  ["Frozen", "გაყინული"],
  ["Previous", "წინა"],
  ["Next", "შემდეგი"],
  ["Submit", "გაგზავნა"],
  ["Create", "შექმნა"],
  ["Save", "შენახვა"],
  ["Cancel", "გაუქმება"],
  ["Close", "დახურვა"],
  ["Edit", "რედაქტირება"],
  ["Delete", "წაშლა"],
  ["Back", "უკან"],
  ["Search...", "ძიება..."],
  ["Search", "ძიება"],
  ["Decrease", "შემცირება"],
  ["Increase", "გაზრდა"],
  ["Unknown", "უცნობი"],
  ["Desc", "კლებადი"],
  ["Asc", "ზრდადი"],
  ["Role: ", "როლი: "],
  ["Admin", "ადმინი"],
  ["Agent", "აგენტი"],
  ["Yes", "კი"],
  ["No", "არა"],
  ["All", "ყველა"],
];

pairs.sort((left, right) => right[0].length - left[0].length);

function replaceDelimited(source, from, to) {
  const escaped = from.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  let output = source;
  output = output.replace(new RegExp(`"${escaped}"`, "g"), `"${to}"`);
  output = output.replace(new RegExp(`'${escaped}'`, "g"), `'${to}'`);
  output = output.replace(new RegExp(`>${escaped}<`, "g"), `>${to}<`);
  return output;
}

function walk(directory) {
  const entries = fs.readdirSync(directory, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      files.push(...walk(fullPath));
    } else if (/\.(ts|tsx)$/.test(entry.name)) {
      files.push(fullPath);
    }
  }
  return files;
}

let changedFiles = 0;
for (const filePath of walk(root)) {
  let next = fs.readFileSync(filePath, "utf8");
  const original = next;
  for (const [from, to] of pairs) {
    next = replaceDelimited(next, from, to);
  }
  if (next !== original) {
    fs.writeFileSync(filePath, next);
    changedFiles += 1;
  }
}

console.log(`Updated ${changedFiles} files`);
