import { CLIENT_INVITE_LINK_STATUS_LABELS as CLIENT_INVITE_LINK_STATUS_DISPLAY_LABELS } from "@/shared/i18n/enumLabels";

export const CLIENT_INVITE_LINK_STATUSES = ["ACTIVE", "USED", "EXPIRED"] as const;
export type ClientInviteLinkStatus = (typeof CLIENT_INVITE_LINK_STATUSES)[number];

export const CLIENT_INVITE_LINK_STATUS_LABELS: Record<ClientInviteLinkStatus, string> = {
  ACTIVE: CLIENT_INVITE_LINK_STATUS_DISPLAY_LABELS.ACTIVE,
  USED: CLIENT_INVITE_LINK_STATUS_DISPLAY_LABELS.USED,
  EXPIRED: CLIENT_INVITE_LINK_STATUS_DISPLAY_LABELS.EXPIRED,
};
