import {
  BUILDING_CONDITION_LABELS as BUILDING_CONDITION_DISPLAY_LABELS,
  CLIENT_STATUS_LABELS as CLIENT_STATUS_DISPLAY_LABELS,
  DEAL_TYPE_LABELS as DEAL_TYPE_DISPLAY_LABELS,
  KITCHEN_TYPE_LABELS as KITCHEN_TYPE_DISPLAY_LABELS,
  RENOVATION_LABELS as RENOVATION_DISPLAY_LABELS,
} from "@/shared/i18n/enumLabels";

export const DEAL_TYPES = ["SALE", "RENT", "DAILY_RENT"] as const;
export type DealType = (typeof DEAL_TYPES)[number];

export const DEAL_TYPE_LABELS: Record<DealType, string> = {
  SALE: DEAL_TYPE_DISPLAY_LABELS.SALE,
  RENT: DEAL_TYPE_DISPLAY_LABELS.RENT,
  DAILY_RENT: DEAL_TYPE_DISPLAY_LABELS.DAILY_RENT,
};

export const CLIENT_STATUSES = ["ACTIVE", "IN_PROGRESS", "ARCHIVED"] as const;
export type ClientStatus = (typeof CLIENT_STATUSES)[number];

export const CLIENT_STATUS_LABELS: Record<ClientStatus, string> = {
  ACTIVE: CLIENT_STATUS_DISPLAY_LABELS.ACTIVE,
  IN_PROGRESS: CLIENT_STATUS_DISPLAY_LABELS.IN_PROGRESS,
  ARCHIVED: CLIENT_STATUS_DISPLAY_LABELS.ARCHIVED,
};

export const RENOVATION_VALUES = [
  "NEW_RENOVATED",
  "RENOVATED",
  "OLD_RENOVATED",
  "NEEDS_RENOVATION",
  "GREEN_FRAME",
  "WHITE_FRAME",
  "BLACK_FRAME",
] as const;
export type Renovation = (typeof RENOVATION_VALUES)[number];

export const RENOVATION_LABELS: Record<Renovation, string> = {
  NEW_RENOVATED: RENOVATION_DISPLAY_LABELS.NEW_RENOVATED,
  RENOVATED: RENOVATION_DISPLAY_LABELS.RENOVATED,
  OLD_RENOVATED: RENOVATION_DISPLAY_LABELS.OLD_RENOVATED,
  NEEDS_RENOVATION: RENOVATION_DISPLAY_LABELS.NEEDS_RENOVATION,
  GREEN_FRAME: RENOVATION_DISPLAY_LABELS.GREEN_FRAME,
  WHITE_FRAME: RENOVATION_DISPLAY_LABELS.WHITE_FRAME,
  BLACK_FRAME: RENOVATION_DISPLAY_LABELS.BLACK_FRAME,
};

export const BUILDING_CONDITIONS = [
  "OLD",
  "NEW",
  "UNDER_CONSTRUCTION",
] as const;
export type BuildingCondition = (typeof BUILDING_CONDITIONS)[number];

export const BUILDING_CONDITION_LABELS: Record<BuildingCondition, string> = {
  OLD: BUILDING_CONDITION_DISPLAY_LABELS.OLD,
  NEW: BUILDING_CONDITION_DISPLAY_LABELS.NEW,
  UNDER_CONSTRUCTION: BUILDING_CONDITION_DISPLAY_LABELS.UNDER_CONSTRUCTION,
};

export const KITCHEN_TYPES = ["SEPARATE", "STUDIO"] as const;
export type KitchenType = (typeof KITCHEN_TYPES)[number];

export const KITCHEN_TYPE_LABELS: Record<KitchenType, string> = {
  SEPARATE: KITCHEN_TYPE_DISPLAY_LABELS.SEPARATE,
  STUDIO: KITCHEN_TYPE_DISPLAY_LABELS.STUDIO,
};

export function isDealType(value: string): value is DealType {
  return (DEAL_TYPES as readonly string[]).includes(value);
}

export function isClientStatus(value: string): value is ClientStatus {
  return (CLIENT_STATUSES as readonly string[]).includes(value);
}

export function isRentDealType(dealType: DealType): boolean {
  return dealType === "RENT" || dealType === "DAILY_RENT";
}
